### ISSUE TITLE
Integrate Rclone

### ISSUE THREAD

**Issue by flxlocle** [DavidBerdik/InfiniDrive#35]
Is there a way to integrate Rclone to work with InfiniDrive? It would be a very useful feature.

Also can InfiniDrive be use to upload a folder?

**Comment by DavidBerdik** [comment]
This is an interesting suggestion. It's not something I want to do right now, but as a long term goal, it is something I am certainly interested in looking in to.

**Comment by DavidBerdik** [comment]
The upcoming release of InfiniDrive v1.0.20 adds support for interacting with InfiniDrive via FTP. The reason behind adding this feature was to allow any programs that support FTP to interact with InfiniDrive as though it was a normal FTP server. Since Rclone supports FTP, the recommended approach to using InfiniDrive with it will be to run InfiniDrive in FTP server mode, and then configure Rclone to connect to the server.
