### ISSUE TITLE
Error when uploading

### ISSUE THREAD

**Issue by AnishDe12020** [DavidBerdik/InfiniDrive#43]

**Comment by AnishDe12020** [comment]
See this - 
![image](https://user-images.githubusercontent.com/63192115/87237915-9d451c00-c419-11ea-9663-dfa01765fc29.png)

**Comment by DavidBerdik** [comment]
Based on the output, I think this is a Google Drive error and not an InfiniDrive error, but I am not sure. Could you please do the following so that I may investigate further?

1. Rerun this command and verify that you can reproduce the issue.
2. If you are able to reproduce the issue, upload the "log.txt" file that should have been generated in the same directory as the "InfiniDrive.py" file.

**Comment by DavidBerdik** [comment]
Due to upcoming changes to Google Drive's storage quota rules resulting in the end of InfiniDrive development, this issue has been closed without completion.

More information on the changes is available at: https://support.google.com/docs/answer/9312312?hl=en#:~:text=After%20June%201%2C%202021&text=Files%20created%20or%20edited%20in,not%20count%20against%20your%20quota.
